# Copyright (c) Qinware Technologies Co., Ltd. 2025. All rights reserved.
# Copyright (c) 2017 - 2025 CHINBOY <qinware@163.com>
# This source file is part of the cskia project
# See https://qinware.com/LICENSE.txt for license information
#
# Created by CHINBOY on 2025/08/03.

set(CSKIA_SOURCE_DIR ${CMAKE_SOURCE_DIR})
set(CSKIA_BINARY_DIR ${CMAKE_BINARY_DIR})
set(CSKIA_INCLUDE_DIR ${CSKIA_SOURCE_DIR}/include)
set(CSKIA_BINARY_INCLUDE_DIR ${CSKIA_BINARY_DIR}/include)
set(CSKIA_TEST_DIR "${CSKIA_SOURCE_DIR}/tests")
set(CSKIA_TEST_BIN_DIR "tests/bin")
set(CSKIA_THIRDPARTY_DIR "${CSKIA_SOURCE_DIR}/thirdparty")

if(WIN32)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/lib)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/lib)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_BINARY_DIR}/bin)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/lib)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/lib)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_BINARY_DIR}/bin)
endif()

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

if(NOT TARGET_TRIPLE_DIRECTORY_PREFIX)
    string(REPLACE "-" "_" TARGET_TRIPLE_DIRECTORY_PREFIX "${CMAKE_SYSTEM_NAME}_${CMAKE_SYSTEM_PROCESSOR}")
    string(TOLOWER "${TARGET_TRIPLE_DIRECTORY_PREFIX}" TARGET_TRIPLE_DIRECTORY_PREFIX)
endif()

if(WIN32)
    set(_CSKIA_APP_PATH "bin")
    set(_CSKIA_APP_TARGET "${CSKIA_PACKAGE_NAME}")

    set(_CSKIA_LIBRARY_BASE_PATH "lib")
    set(_CSKIA_LIBRARY_PATH "${_CSKIA_LIBRARY_BASE_PATH}")
    set(_CSKIA_LIBEXEC_PATH "bin")
    set(_CSKIA_DATA_PATH "share/${CSKIA_PACKAGE_NAME}")
    set(_CSKIA_BIN_PATH "bin")
    set(_CSKIA_LIBRARY_ARCHIVE_PATH "${_CSKIA_BIN_PATH}")
else()
    include(GNUInstallDirs)
    set(_CSKIA_APP_PATH "${CMAKE_INSTALL_BINDIR}")
    set(_CSKIA_APP_TARGET "${CSKIA_PACKAGE_NAME}")
    set(_CSKIA_LIBRARY_BASE_PATH "${CMAKE_INSTALL_LIBDIR}") # 暂时写死
    set(_CSKIA_LIBRARY_PATH "${_CSKIA_LIBRARY_BASE_PATH}")
    set(_CSKIA_LIBEXEC_PATH "${CMAKE_INSTALL_LIBEXECDIR}")
    set(_CSKIA_DATA_PATH "${CMAKE_INSTALL_DATAROOTDIR}/${CSKIA_PACKAGE_NAME}")
    set(_CSKIA_BIN_PATH "${CMAKE_INSTALL_BINDIR}")
    set(_CSKIA_LIBRARY_ARCHIVE_PATH "${_CSKIA_LIBRARY_PATH}")
endif()

if(APPLE)
    set(_RPATH_BASE "@executable_path")
    set(_LIB_RPATH "@loader_path")
elseif(WIN32)
    set(_RPATH_BASE "")
    set(_LIB_RPATH "")
else()
    set(_RPATH_BASE "\$ORIGIN")
    set(_LIB_RPATH "\$ORIGIN;")
endif()

set(CSKIA_APP_PATH "${_CSKIA_APP_PATH}")
set(CSKIA_APP_TARGET "${_CSKIA_APP_TARGET}")
set(CSKIA_LIBRARY_BASE_PATH "${_CSKIA_LIBRARY_BASE_PATH}")
set(CSKIA_LIBRARY_PATH "${_CSKIA_LIBRARY_PATH}")
set(CSKIA_LIBRARY_ARCHIVE_PATH "${_CSKIA_LIBRARY_ARCHIVE_PATH}")
set(CSKIA_LIBEXEC_PATH "${_CSKIA_LIBEXEC_PATH}")
set(CSKIA_DATA_PATH "${_CSKIA_DATA_PATH}")
set(CSKIA_BIN_PATH "${_CSKIA_BIN_PATH}")
